spring.application.name=delivery-api

# Configuração do servidor
server.port=8080

# Configuração do H2 Database
spring.datasource.url=jdbc:h2:mem:deliverydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configurações de desenvolvimento
spring.devtools.restart.enabled=true

# Configurações específicas para JDK 21
spring.jpa.open-in-view=false
logging.level.org.springframework.web=DEBUG


# Swagger / OpenApi
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

# Endpoints do actuator
management.endpoints.web.exposure.include=health,info,metrics,env,prometheus

# Mostrar detalhes do health
management.endpoint.health.show-details=always

# Habilitar informações via properties
management.info.env.enabled=true

# Dados da aplicação
info.app.name=Delivery API
info.app.description=API de sistema de delivery
info.app.version=1.0.0
info.app.author=Elaine

# Ambiente
info.ambiente.perfil=desenvolvimento
info.ambiente.java.version=${java.version}
info.ambiente.spring.version=3.4.5

# Contato
info.contato.email=teste@gmail
info.contato.github=https://github.com/seu-usuario

#Habilitar informações do Git
management.info.git.enabled=true
management.info.git.mode=full

